### ISSUE TITLE
Additional command line arguments are not quoted properly

### ISSUE THREAD

**Issue by c0wg0d** [Youda008/DoomRunner#103]
I am trying to create a preset that plays the Doom done Quick demo file.  My Additional command line arguments is `-playdemo "../../Demos/Doom done Quick/DDQ-EP1.LMP"`.  When I try to launch with this, I get the error `W_GetNumForName: "../../D not found!`  It seems like the quotes are lost or are wrapped inside other quotes upon launch which messes up the command.  If I run this from the command line outside of Doom Runner it works fine:

`chocolate-doom.exe -iwad "../../IWADs/Doom/DOOM.WAD" -playdemo "../../Demos/Doom done Quick/DDQ-EP1.LMP"`

My folder structure is as follows:

```
Doom\IWADs\Doom\DOOM.WAD
Doom\Source Ports\Chocolate Doom\chocolate-doom.exe
Doom\Demos\Doom done Quick\DDQ-EP1.LMP
```

**Comment by Sohl42** [comment]
Using additional command line arguments without quotes around the path seems to work out.
For example: `-playdemo ../../Demos/ep1-513.lmp`
Resulting in: `./dsda-doom.exe -iwad "../../IWADS/DOOM.WAD" -playdemo ../../Demos/ep1-513.lmp`

**Comment by c0wg0d** [comment]
Yeah, spaces cause an issue, but you're right that if your path has no spaces, omitting the quotes does work.  I would still like to see this bug get fixed though, if anyone is still maintaining this project.

**Comment by Youda008** [comment]
Hm, this is tricky. Either Qt or Windows automatically adds quotes around parameters that contain spaces and automatically escape-out quotes that you add manually, resulting in command containing `-playdemo \"../../Demos/Doom done Quick/DDQ-EP1.LMP\"` which the Chocolate Doom apparently can't handle.
These problems with quoting are never-ending story (i already reworked the quoting mechanisms several times) because Windows behaves differently than Linux and it's really hard to write a code that works for both and is not a complete mess.
But i'm not giving up yet.

**Comment by Youda008** [comment]
Should be fixed now.
