### ISSUE TITLE
Feature request: have the option to load certain mods before the maps in the load order?

### ISSUE THREAD

**Issue by thecnoNSMB** [Youda008/DoomRunner#133]
I've noticed that the load order forcing all mods to come in front of the maps in the load order causes minor issues with the [Doom 2 Minor Sprite Fixing Project](https://www.doomworld.com/forum/topic/62403), and probably other simple asset replacement mods, when the map also intends to replace those assets. In the sprite fixing case, that mod fixes errors with the "SAVE GAME", "HEY, NOT TOO ROUGH!", and other menu text sprites, which causes them to stand out like a sore thumb when a mapset restyles all the menu options. It isn't that big of a deal, as turning off the relevant asset replacement mod fixes it, but it might be an easy enough feature to add to be worth it.

**Comment by thecnoNSMB** [comment]
I have discovered a couple workarounds: you can load the map as a mod to manually put it at the bottom of the load order, or (depending on your source port; in my case this was only possible for DSDA-Doom) put whatever minor mods you want in that source port's autoload folder(s) manually. So, again, this is quite minor.

**Comment by Youda008** [comment]
@thecnoNSMB Hi. Sorry for answering so late. I was busy at that time and then completely forgot about it.

This is unfortunatelly one of the main design flaws of this launcher, and there is no simple way to fix it without ruining the simplicity of the UI.

However as you already figured out, there is a feasible workaround that i always recommend, and that is manually adding the map file to the mod list and specifying the order there. At least i made this easy by enabling drag&drop from the map list to the mod list.

Since this relatively pain-less workaround exists and since this is not very common scenario, i don't think it's worth investing the effort into some bigger rework that would allow to specify the order in a more elegant way.

**Comment by thecnoNSMB** [comment]
I did not know that you could drag and drop from the map list to the mod list, that is very helpful!

**Comment by VGkav** [comment]
The mods should be loaded last, I think. First the maps and then the mods. Because some wads, especially old ones, make silly resource changes. The gameplay mods are generally more modern and should be loaded last in order to overwrite everything they want.

**Comment by Youda008** [comment]
@VGkav In 90% yes. There are some cases (one desribed by @thecnoNSMB) where the maps must be loaded after, but they are so rare that it does not make sense to rework the UI because of them.
Of course i could make a checkbox ☑ _Load map files after mod files_,  but then someone else would come and say
"Hey, let me customize the load order even more, i want to load first **mod1**, then **map1**, then **mod2**, then **map2**",
and i will have nothing else to say to him than "Just put everything in the mod list and ignore the map list",
which is what you can already do now, and it doesn't require cluttering the UI with more elements.

**Comment by VGkav** [comment]
Oh, yeah, now I re-read the first post and understand the problem.

@thecnoNSMB The sprite fixing mod should not be touching menu graphics. I would open it in SLADE and delete its menu replacements. Or better yet, use a better sprite/animation fixing mod.

**Comment by thecnoNSMB** [comment]
The sprite fixing mod intentionally touches menu graphics because some of the menu graphics need fixing (The "HEY, NOT TOO ROUGH" sprite I mentioned earlier has its comma cut off at the bottom in vanilla, for instance), and is designed to sit in your source port's autoload folder, which is where I ended up putting it. I understand @Youda008's argument, though, so I'm closing the issue on the understanding that it's essentially a "wontfix".

**Comment by Youda008** [comment]
Ok, checkbox added and released.
