### ISSUE TITLE
SIGIL II - Cannot set starting map

### ISSUE THREAD

**Issue by buvk** [Youda008/DoomRunner#137]
When loading SIGIL II as a map pack, the following error occurs in DoomRunner:

![image](https://github.com/Youda008/DoomRunner/assets/2666951/097924c6-bab0-4c4c-b5f2-0c20d3597a26)

**Comment by NightFright2k19** [comment]
For clearification: Game can still be launched and it's possible to select and load the episode through the ingame menu. This error is probably just due to the fact that there's currently no way to directly jump to E6M1 through the launcher.

**Comment by Youda008** [comment]
Is this wad somewhere free to download? I would like to see what's inside and how it's detected in DoomRunner.

**Comment by DanilaSpevak** [comment]
> Is this wad somewhere free to download? I would like to see what's inside and how it's detected in DoomRunner.

Both SIGIL are available on Romero's website

https://romero.com/sigil

**Comment by hmrks** [comment]
Note that the error message disappears if you also select the Sigil 1 WAD. I guess Sigil II expects a 5th episode to be present?

**Comment by NightFright2k19** [comment]
It does not. Neither is that stated in the readme nor do ports such as Woof! (tested) require it.

Also note that loading any other pwad alongside Sigil 2, including Sigil 1, will have an impact on your gameplay experience (Spider Masterminds are tougher) due to DEHACKED code. That also covers the original episodes, btw, so this one isn't really suited for integration purposes like WadSmoosh, either. Unless you undo the hack, which in return alters the Sigil 2 experience to some degree.

**Comment by Youda008** [comment]
Ok, this is just a too generic regular expression, the launcher thinks that it is SIGIL 1 and attemps to set the starting map from SIGIL 1.
Luckily, if you just ignore the message, you can still use it, even launch the first map, you just have to manually select the E6M1 from the drop down list.
I will fix this next weekend i hope.

**Comment by Youda008** [comment]
Fixed. Release will hopefully be soon.
