### ISSUE TITLE
[suggestion] Remembering window size, arrangement and position

### ISSUE THREAD

**Issue by mstempell** [Youda008/DoomRunner#143]
Would be great if the program remembered its window size, position, and arrangement (related to another suggestion I got), when closed and reopened.

**Comment by Youda008** [comment]
But this is already there for a long time. What's your operating system?

**Comment by mstempell** [comment]
It's: Windows 10 Pro / Version 22H2 / Build 19045.3930 / Windows Feature Experience Pack 1000.19053.1000.0

And testing some more after your answer, window size is actually remembered, yes.
So sorry for mentioning that.

Then it's just that the window pops up on the upper left, not where it was when closed.
And if closed maximized, it's not exactly maximized when reopened.

**Comment by Youda008** [comment]
In the past there was an issue with secondary monitors, where if you closed the app on an secondary monitor, then disconnected the monitor (laptop and external monitor) and open the app again, the window would not be visible and movable, because it would appear at virtual coordinates that no longer exist.
That's why i have to re-center the window everytime. If i find a workaround, it can be removed.

**Comment by Youda008** [comment]
I found a way to detect if the last known screen coordinates are still valid, so i think it's now working correctly.
It will be part of 1.8.3 release.

**Comment by Youda008** [comment]
I belive this can now be closed.
