### ISSUE TITLE
Use +map instead of -warp for map loading

### ISSUE THREAD

**Issue by nashmuhandes** [Youda008/DoomRunner#18]
+map is more robust, and can support non-standard map name, for example, in ZDoom Executor, with Kinsie's Test Map in my autoload, I can type 'test' in the map slot (the map's lump is named TEST).

Retain the current combo box list of maps, but also allow the user to type an arbitrary map label (this mimics ZDE's behavior).

**Comment by Youda008** [comment]
This is good idea actually. I read the zdoom wiki and it says it can indeed be used instead, except that it needs to be in different format (`+map E2M3` instead of `-warp 2 3` and `+map MAP23` instead of `-warp 23`), but that's actually better for me, because there will no longer be a need for conversion. 👍

**Comment by Youda008** [comment]
Done. It will be part of next release.

**Comment by nashmuhandes** [comment]
Thank you. Upon reading my original post, I realized I didn't describe it clearly enough, but it looks like you figured it out already, however, just in case -

The reason why +map is better is because you can do, for example, gzdoom.exe +map MyFancyMap - there are projects/TCs that don't use the typical Doom ExMx or MAPxx format. :)

Looking forward to try the next release. :)
