### ISSUE TITLE
'isPortableInstallation' was not declared in this scope

### ISSUE THREAD

**Issue by SilverKeeper** [Youda008/DoomRunner#196]
Trying to build the new release on Linux, make complains about isPortableInstallation() not being declared in "Source/EngineTraits.cpp" Line 345; and it's true, the function isn't declared on that file.

**Comment by Youda008** [comment]
Thanks for reporting, fixed.
But this issue was in master branch, which is a constant work-in-progress branch and is not guaranteed to work.
For the new release you need to switch to tag [v1.8.3](https://github.com/Youda008/DoomRunner/tree/v1.8.3) or branch [release-v1.8.3](https://github.com/Youda008/DoomRunner/tree/release-v1.8.3)
