### ISSUE TITLE
Crash when trying to select a config file without a engine selected first.

### ISSUE THREAD

**Issue by PopeRigby** [Youda008/DoomRunner#37]
My shell is telling me this:
```
fish: “doomrunner” terminated by signal SIGSEGV (Address boundary error)
```

Any way I can get a trace?

**Comment by Youda008** [comment]
I don't think so, i have only release build (without debug symbols) on Linux.
You need to tell me what exactly you and i have to reproduce it in my debug run.
But first of all, which version do you use? The one from release page, or your own build from master? Because i remember i've already discovered some problems and fixed them, they are just not released yet.

**Comment by PopeRigby** [comment]
Good point. I'll check to see if I can reproduce on master.

**Comment by PopeRigby** [comment]
My bad. It seems you fixed it in master. It just doesn't let me select a config file if an engine isn't selected first. Maybe have a popup telling you to select an engine?

**Comment by Youda008** [comment]
That sounds like a good idea, but i don't know how to do it. Maybe i'll figure it out some day.
