### ISSUE TITLE
Mod directory not working

### ISSUE THREAD

**Issue by Sam9889** [Youda008/DoomRunner#57]
I am running version 1.5.1 on windows 10.
I am having issue putting mods files into a folder and selecting that folder so I can use them at once instead of selecting them manually.
If I add mods files manually and select them it works.
But if I put those same mods into a folder then add that folder in "Add mods" box and select the folder, the mod(s) inside the folder do not work.

**Comment by codeflorist** [comment]
i believe this is a misunderstanding. i think the mod directory feature does not mean, that you can put multiple mods (.pk3) files in a directory and they all get loaded automatically. it means, that you can specify a folder, that contains the files of a singular mod (e.g. an extracted pk3-file).

it would however be a very handy feature.

**Comment by Youda008** [comment]
It seems @codeflorist is right. 
According to this https://forum.zdoom.org/viewtopic.php?f=4&t=35736 the directory is not supposed to contain multiple `wad` or `pk3` files, it's supposed to contain the unpacked content of a single `wad` or `pk3` file.

**Comment by codeflorist** [comment]
turns out this actually IS (somewhat) possible:

1. create a `gameinfo.txt` inside a folder (e.g. `General Doom Mods`.
2. put something like this inside it:
```
LOAD = "../../general/droplets_1.3.1.pk3"
LOAD = "../../general/ULTIMATE-CHEAT-MENU-PC.zip"
LOAD = "../../general/Resurrectupdate.pk3"
LOAD = "NeuralUpscale2x_v1.0.pk3"
LOAD = "marcelus_hd_sprites_1082022.pk3"
LOAD = "DTHP+PBR Updated.pk3"
LOAD = "pk_doom_sfx_20120224.wad"
LOAD = "Universal Ambience_v1.7.pk3"
LOAD = "CosmoAmbience Script edited_v1.7.pk3"
LOAD = "Ambient decorations_v1.7.pk3"
LOAD = "cheello_voxels.zip"
```
(as you can see, relative paths are possible.)

now you can add the directory as a mod to DoomRunner and it will load these mods.

the downside is, this works only with one directory, not multiple ones.

see https://zdoom.org/wiki/GAMEINFO for details
