### ISSUE TITLE
Unable to launch multiplayer game via Doom Runner

### ISSUE THREAD

**Issue by mikeangelparra** [Youda008/DoomRunner#71]
I am using the linux version of gzdoom 4.8.2, not the flatpak version. 

When I try and launch a multiplayer game through Doom Runner, I receive no feedback and nothing happens. I try and join the game on another PC in hopes it launched in the background, but failed to join. If I copy the command provided by Doom Runner to launch a multiplayer game into the terminal AFTER attempting on Runner, it will say port already in use. It seems Runner leaves an instance of gzdoom hogging port 5029. If I run "killall -9 gzdoom" and then try again via terminal, multiplayer launches just fine.

**Comment by Youda008** [comment]
Hm, that's strange. Until 1.6 DoomRunner doesn't hold any joinable instance of the Doom process, it is started detached and left alone, so when the Doom quits, the process should exit and release all resources immediatelly.
I tried it myself in my Ubuntu, and the GZDoom quited normally. I don't think this is an issue of DoomRunner. Something seems fishy in your system.
Please beware that when GZDoom ends, it leaves this kind of "good bye" window open until clicked on the screen.
![obrazek](https://user-images.githubusercontent.com/20306543/190493558-41cbeb72-ce7c-4980-81d4-8ed85f65b9dd.png)
Maybe it's stuck in this phase?

**Comment by Youda008** [comment]
@mikeangelparra I did some testing and i found what's happening there.
The problem is that unlike in Windows, in Linux the GZDoom doesn't show the loading dialog that says "Waiting for players", instead it just writes it to a terminal and waits. That means if you click Launch from DoomRunner that was not started from terminal, this output gets thrown away and not displayed, so it seems like nothing is happening, but the GZDoom is already running and waiting for clients to join the server. And if you click Launch again, it will try to start second GZDoom and that one will fail because the port is already used by the first one.

Look at this
![image](https://user-images.githubusercontent.com/20306543/192147363-3e285a92-2042-4b34-992d-851445b91db8.png)

For these cases i created this feature
![image](https://user-images.githubusercontent.com/20306543/192147545-50ab76d1-55b4-4a36-afc2-3522fcb20ce4.png)
I suggest you use it.

**Comment by Youda008** [comment]
In version 1.6.1 I improved the launcher's behaviour in this scenario on Linux.
But those who already used 1.6 at least once will still have to manually enable the "Show engine's standard output" option shown above, because 1.6 initialized it to off by default.

**Comment by mikeangelparra** [comment]
Thank you so much! Sorry it took me so long to get back to you, been busy with work lately. Your work on this project is much appreciated, thank you again
