### ISSUE TITLE
[BUG] 1.7 is a bit chaotic in windows

### ISSUE THREAD

**Issue by ibin7777** [Youda008/DoomRunner#89]
![image](https://user-images.githubusercontent.com/64576479/204117703-c3f47c88-2c41-44ad-b29b-2ad474145bb5.png)
![image](https://user-images.githubusercontent.com/64576479/204117840-4fcc86fb-1157-4f7e-b7ef-0640ae5502d1.png)
From a glance I'm seeing 3 issues:
1. "Mod no longer exists" for project brutality despite it still present (might be an issue for mods that are folders, can't confirm)
2. Content sections are pitch black, which is a bit off from a comfortable dark
3. All frames are white, and texts are also white, making them unrecognizable
No idea what causes them, I hope it helps. I can do any follow up under instructions if there's more information you need.

**Comment by ibin7777** [comment]
![image](https://user-images.githubusercontent.com/64576479/204117937-87344f2e-c670-4995-b2dd-75cb5d684826.png)
Follow up: 1.7 seems have made changes to the options.json and caused some error when I roll back to 1.6.5

I used the good old ctrl+Z in that folder and rolled all the way back, luckily it worked and my json file was rescued.

**Comment by Berzasperd** [comment]
Confirmed on Windows 10 22H2.  The screenshots from @ibin7777 's first post are how Doomrunner looks on first launch.  For those of you that may have seen the beta build, this is a bit of a surprise.  To use the fully functional Dark theme, set your Application style to Fusion in the Initial setup menu.

![doomrunner_theme_options](https://user-images.githubusercontent.com/71313143/204120240-ec7a43a0-72da-448f-85eb-31d9a1cc8bac.png)

The System default and windowsvista application styles are the main ones having trouble.  It looks like button, menu, and menu text colors are using the old Light theme colors.  Setting Dark (override) while System default is active will automatically switch the Application style to Fusion.  Setting Dark (override) while windowsvista is active doesn't change anything.  Setting Dark (override) first and then selecting System default doesn't change anything.

As for the other style that seems to mostly normally, the Windows style has sharp rectangular white borders around the main fields and keeps all the corners sharp rather than rounded.

![doomrunner_theme_windowsstyle](https://user-images.githubusercontent.com/71313143/204120411-8bca1b22-d0bf-413b-b88b-158a8c1c88e5.png)

The default settings for the theme right now are System default Application style and System default Color scheme.  Hopefully that helps.

**Comment by Youda008** [comment]
The theme settings are coded so that when you click "Dark (override)", it automatically selects style "Fusion". The standard "windowsvista" style does not work with dark colors and there is nothing i can do about that.
The problem here is probably with autodetection - when the colors are set automatically based on Windows settings.

**Comment by Youda008** [comment]
Fixed. I will wait a day or two for potential other bug reports and then make a release.
