### ISSUE TITLE
[BUG] 1.7 has a json compatibility issue when handling mod folders

### ISSUE THREAD

**Issue by ibin7777** [Youda008/DoomRunner#90]
![image](https://user-images.githubusercontent.com/64576479/204120804-207432ab-85f0-4b9c-9722-c1a0ef88ff46.png)
Updated from 1.6.5, the 1.7 has some sort of issue when dealing with mods that are folders in the old json file,
As you can see from the screenshot, those in red are all the mods that is in folder form.
despite the 1.7 launcher saying "does not exist", I can still open file location and find that mod folder.
![image](https://user-images.githubusercontent.com/64576479/204120979-ce385962-e436-433a-8dc7-f5c1fa7200a6.png)
Also, if I try to roll back to 1.6.5, then this happens and prompt me with a series of other error messages.
I also tested newly added mod folder in 1.7, everything seems working fine. So this might not be an issue for anyone using dommrunner for the first time.
However, I would suggest avoiding changes on the augorithm to handle json file since doing it might corrupts the old save. If that's something unavoidable, please inform in the release note so that we acknowledge the necessity of backing up the old json file.

**Comment by Youda008** [comment]
Ah yes, i forgot about directories, i will fix that.

Regarding options incompatibility going from 1.7 to 1.6.x, it's kinda expected, i cannot add code to the past. Old launcher versions cannot be made compatible with the new ones, because the new format doesn't exist yet at the time of writing of the old version. Backward compatibility from 1.6.x to 1.7 should work, i tested that multiple times.
It was mentioned in `changelog.txt`, but i should have probably mention that in release description too.

**Comment by Youda008** [comment]
Fixed. I will wait a day or two for potential other bug reports and then make a release.
